### ISSUE TITLE
Pre-built binary not working

### ISSUE THREAD

**Issue by issacclee** [adobe/USD-Fileformat-plugins#24]
### Expected Behaviour
Pre-built binary usdcat can convert fbx into usd
### Actual Behaviour
usdcat prompt with an error `Cannot determine file format for @test/diaiguanmu.fbx@`
### Reproduce Scenario (including but not limited to)
I used usdcat with these parameters
`./bin/usdcat -o diaiguanmu.usd ./test/diaiguanmu.fbx`
#### Platform and Version
ubuntu22.04.4 in windows10 linux subsystem
The pre-built binary was from the release build "USD-2405-Artifacts"

**Comment by kwblackstone** [comment]
Hello, the USD-XXX-Artifacts are just vanilla USD and currently only used in the CI system to test the plugins.  Once you have USD locally you still need to follow the instructions to build and install the plugins properly in order to use them.  Instructions here:  https://github.com/adobe/USD-Fileformat-plugins?tab=readme-ov-file#2-get-it
